# Generated by Django 4.0.3 on 2022-04-10 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_verificationcode_uuid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='uuid_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL),
        ),
    ]
