# Generated by Django 4.0.3 on 2022-04-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_verificationcode_uuid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='verification_code',
            field=models.CharField(max_length=6),
        ),
    ]
