# Generated by Django 4.0.3 on 2022-05-14 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_verificationcode_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prefference',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefference_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrefference',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prefference_name', models.CharField(max_length=100)),
                ('liked', models.BooleanField()),
                ('uuid_prefference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_prefference', to='backend.prefference')),
                ('uuid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
