# Generated by Django 4.0.3 on 2022-05-14 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_group_prefference_userprefference'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('uuid_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_prefference', to='backend.group')),
                ('uuid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
