# Generated by Django 4.0.3 on 2022-05-14 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='ending_hour',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='starting_hour',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='UserActivityRating',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_rating', models.FloatField()),
                ('uuid_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_activity', to='backend.activity')),
                ('uuid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityParticipants',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('participant_name', models.CharField(max_length=100)),
                ('uuid_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_activity', to='backend.activity')),
                ('uuid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
