# Generated by Django 4.0.3 on 2022-05-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_activity_activity_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
