# Generated by Django 4.0.3 on 2022-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_useringroup_uuid_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_description',
            field=models.CharField(default='default', max_length=350),
            preserve_default=False,
        ),
    ]
