# Generated by Django 4.0.3 on 2022-06-18 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_group_group_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_description', models.CharField(max_length=350)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post_likes', models.IntegerField()),
                ('post_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_prefference', to='backend.group')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
