# Generated by Django 4.0.3 on 2022-06-18 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_post_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_groups', to='backend.group'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
