# Generated by Django 4.0.3 on 2022-06-21 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_likes',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_bys', to=settings.AUTH_USER_MODEL)),
                ('post_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_uuids', to='backend.post')),
            ],
        ),
    ]
